export const routesEnUs = [
    { label: 'Avatar', name: 'Avatar', url: '/components/avatar' },
    { label: 'Backplate', name: 'Backplate', url: '/components/backplate' },
    { label: 'Badge', name: 'Badge', url: '/components/badge' },
    { label: 'Button', name: 'Button', url: '/components/button' },
    { label: 'Check', name: 'Check', url: '/components/check' },
    { label: 'Container', name: 'Container', url: '/components/container' },
    { label: 'Folding', name: 'Folding', url: '/components/folding' },
    { label: 'Grid', name: 'Grid', url: '/components/grid' },
    { label: 'Input', name: 'Input', url: '/components/input' },
    { label: 'List', name: 'List', url: '/components/list' },
    { label: 'Modal', name: 'Modal', url: '/components/modal' },
    { label: 'Navbar', name: 'Navbar', url: '/components/navbar' },
    {
        label: 'Number Field',
        name: 'NumberField',
        url: '/components/number-field',
    },
    { label: 'Popup', name: 'Popup', url: '/components/popup' },
    // {label:'Segmented', name: 'Segmented', url: '/components/segmented' },
    // {label:'Select', name: 'Select', url: '/components/select' },
    { label: 'Sidebar', name: 'Sidebar', url: '/components/sidebar' },
    { label: 'Switch', name: 'Switch', url: '/components/switch' },
    { label: 'Text Field', name: 'TextField', url: '/components/text-field' },
    { label: 'Toolbar', name: 'Toolbar', url: '/components/toolbar' },
    { label: 'View', name: 'View', url: '/components/view' },
]
