import { MyRoute } from './types'

export const routesZhCn: MyRoute[] = [
    { label: '头像', name: 'Avatar', url: '/components/avatar' },
    { label: '背景板', name: 'Backplate', url: '/components/backplate' },
    { label: '徽章', name: 'Badge', url: '/components/badge' },
    { label: '按钮', name: 'Button', url: '/components/button' },
    { label: '单/多选', name: 'Check', url: '/components/check' },
    { label: '碎片', name: 'Chip', url: '/components/chip' },
    { label: '窗口', name: 'Container', url: '/components/container' },
    { label: '折叠', name: 'Folding', url: '/components/folding' },
    { label: '栅格', name: 'Grid', url: '/components/grid' },
    { label: '输入框', name: 'Input', url: '/components/input' },
    { label: '列表', name: 'List', url: '/components/list' },
    { label: '模态框', name: 'Modal', url: '/components/modal' },
    { label: '导航条', name: 'Navbar', url: '/components/navbar' },
    {
        label: '数字输入框',
        name: 'NumberField',
        url: '/components/number-field',
    },
    { label: '弹出', name: 'Popup', url: '/components/popup' },
    // {label:'单/多选组件', name: 'Segmented', url: '/components/segmented' },
    // { label: '选择框', name: 'Select', url: '/components/select' },
    { label: '侧边栏', name: 'Sidebar', url: '/components/sidebar' },
    { label: '开关', name: 'Switch', url: '/components/switch' },
    { label: '文本输入框', name: 'TextField', url: '/components/text-field' },
    { label: '工具栏', name: 'Toolbar', url: '/components/toolbar' },
    { label: '视图', name: 'View', url: '/components/view' },
]
